# -*- coding: utf-8 -*-
"""RAG_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hGIAaxXz_hVOzPjSpDyqkkZ2nlpsybgq
"""
import os

from langchain_community.document_loaders import PyPDFLoader


os.environ["OPENAI_API_KEY"] = input("Enter your OpenAI API Key: ")

pdf_url = "https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-53r5.pdf"
pdf_path = "nist_800_53_r5.pdf"

import requests
response = requests.get(pdf_url)
with open(pdf_path, "wb") as f:
    f.write(response.content)

print("✅ Downloaded: NIST SP 800-53 Rev. 5 – Security and Privacy Controls")

"""Step 2"""
loader = PyPDFLoader("nist_800_53_r5.pdf")

from langchain_community.document_loaders import PyPDFLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter

loader = PyPDFLoader("nist_800_53_r5.pdf")
pages = loader.load()

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=100
)
documents = text_splitter.split_documents(pages)

print(f"✅ Total chunks created: {len(documents)}")
print(f"📄 Sample chunk:\n\n{documents[0].page_content[:500]}")

"""Step 3"""



from langchain.embeddings import HuggingFaceEmbeddings

# Use local embedding model
embedding_model = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")

from langchain.vectorstores import FAISS

sample_documents = documents[:100]  # safe for local model

vectorstore = FAISS.from_documents(sample_documents, embedding_model)

vectorstore.save_local("faiss_index")

print("✅ Step 3 complete with local embeddings.")

"""Step 4

"""


from langchain.chains import RetrievalQA
from langchain_openai import ChatOpenAI
from langchain.vectorstores import FAISS
from langchain.embeddings import HuggingFaceEmbeddings

# Reload local embeddings
embedding_model = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")

# Reload FAISS with safe deserialization
vectorstore = FAISS.load_local("faiss_index", embedding_model, allow_dangerous_deserialization=True)

# Create retriever
retriever = vectorstore.as_retriever()

# ✅ Use new ChatOpenAI from langchain-openai
llm = ChatOpenAI(model_name="gpt-3.5-turbo", temperature=0)

# Build RAG chain
qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    retriever=retriever,
    return_source_documents=True
)


from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, pipeline
from langchain.llms import HuggingFacePipeline

# Use a lightweight model compatible with Colab
model_id = "google/flan-t5-small"

# Load tokenizer and model
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForSeq2SeqLM.from_pretrained(model_id)

# Set up text-generation pipeline
pipe = pipeline(
    "text2text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=256,
    temperature=0.7,
)

# Wrap it with LangChain
llm = HuggingFacePipeline(pipeline=pipe)

from langchain.chains import RetrievalQA

qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    retriever=retriever,
    return_source_documents=True
)

query = "What is credential dumping?"
response = qa_chain(query)

print("🔍 Question:", query)
print("\n🧠 Answer:\n", response['result'])
print("\n📄 Source:\n", response['source_documents'][0].page_content[:300])

questions = [
    "What is credential dumping?",
    "How can you mitigate lateral movement in a network?",
    "What are the privacy controls recommended by NIST?",
    "Explain access control as per NIST 800-53.",
    "What is incident response planning?"
]

for q in questions:
    response = qa_chain(q)

    print(f"\n🔍 Question: {q}")
    print(f"\n🧠 Answer:\n{response['result']}")

    print(f"\n📄 Source snippet:\n{response['source_documents'][0].page_content[:300]}...")
    print("=" * 100)